services:
  redis:
    image: 'redis/redis-stack:latest'
    container_name: 'redis'
    ports:
      - '6379:6379'
      - '8001:8001'
    restart: on-failure

  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    restart: on-failure
